name: Deploy Backend

on:
  push:
    branches:
      - main

jobs:
  deploy-backend:
    name: Deploy Backend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Project
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install Dependencies
        run: |
          cd Scraper
          npm install

      - name: Run backend script
        run: |
          cd Scraper
          npx ts-node src/split.ts

      - name: Deploy to gh-pages branch
        run: |
          git checkout --orphan gh-pages

          git rm -rf .

          echo "node_modules/" > .gitignore
          echo "Scraper/" >> .gitignore

          git add .

          git -c user.name='github-actions' -c user.email='actions@github.com' commit -m "Deploy backend"

          git push -f origin gh-pages
